### ISSUE TITLE
Add developer warnings

### ISSUE THREAD

**Issue by chandlerprall** [chandlerprall/insula#4]
When `process.env === "development"`, console.warn when an invalid selector (non-array) is used for state access, setting, or subscription

**Comment by hartzis** [comment]
what about the approach react takes with `process.env !== 'production'`?

**Comment by chandlerprall** [comment]
@hartzis @michaelmerrill see [relevant tests](https://github.com/chandlerprall/insula/blob/feature/developer-warnings/src/tests/Store.jest.js#L457-L514)
