### ISSUE TITLE
Increase Developer contributions?

### ISSUE THREAD

**Issue by hartzis** [chandlerprall/insula#7]
Thoughts on making the project a little more friendly as easier to contribute to.
- [x] contribute readme or contribute/development section in readme
- [x] ~~fully es6+ code, i'd argue most open source devs want to write in es6+ 😸~~
- [x] travis-ci integration for tests, help with a piece of mind for PRs 🎉

Just a few small ideas to start a convo.

**Comment by chandlerprall** [comment]
The reason this isn't ES6 is to provide performance by default. It is more difficult to guarantee Babel's (or another transpiler) output will be performant.

I really like the other suggestions.

**Comment by hartzis** [comment]
Good point on the ES6+. Examples and tests can be ES6+.

**Comment by chandlerprall** [comment]
#8 adds `CONTRIBUTING.md`

**Comment by chandlerprall** [comment]
circleci has been added to the project
